// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNR2BcbFPTFdnher5ehmZvFN40aUpJzPg',
    appId: '1:1034661281054:web:a932d15c73ce994c7a5d0f',
    messagingSenderId: '1034661281054',
    projectId: 'flutter-ai-playground-2379c',
    authDomain: 'flutter-ai-playground-2379c.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-2379c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbD1fZciX5h5HzDUvOKAV8EbGavUYsPZE',
    appId: '1:1034661281054:android:604f72c65d181f777a5d0f',
    messagingSenderId: '1034661281054',
    projectId: 'flutter-ai-playground-2379c',
    storageBucket: 'flutter-ai-playground-2379c.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIUYjcnLwm6v963Vs9mf2M3DJT1NMbiTo',
    appId: '1:1034661281054:ios:93a4c86769e8cdfe7a5d0f',
    messagingSenderId: '1034661281054',
    projectId: 'flutter-ai-playground-2379c',
    storageBucket: 'flutter-ai-playground-2379c.firebasestorage.app',
    iosBundleId: 'com.jobscope.jobscope',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIUYjcnLwm6v963Vs9mf2M3DJT1NMbiTo',
    appId: '1:1034661281054:ios:4901b35c89b3f4b37a5d0f',
    messagingSenderId: '1034661281054',
    projectId: 'flutter-ai-playground-2379c',
    storageBucket: 'flutter-ai-playground-2379c.firebasestorage.app',
    iosBundleId: 'com.Raghad.jobscope',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNR2BcbFPTFdnher5ehmZvFN40aUpJzPg',
    appId: '1:1034661281054:web:a297b9cba579e4d77a5d0f',
    messagingSenderId: '1034661281054',
    projectId: 'flutter-ai-playground-2379c',
    authDomain: 'flutter-ai-playground-2379c.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-2379c.firebasestorage.app',
  );

}