// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY4dIRy7JS-wZOTrSrpXgaZ__Sg1fkZa0',
    appId: '1:1060937525212:web:a48e6ca4a162cf782b5119',
    messagingSenderId: '1060937525212',
    projectId: 'jobscope-app',
    authDomain: 'jobscope-app.firebaseapp.com',
    storageBucket: 'jobscope-app.firebasestorage.app',
    measurementId: 'G-XNGDCJ8FW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv8QDRHTJ85gKYM4s9MgShDZ6NBqqkgl0',
    appId: '1:1060937525212:android:605b47830d15ab282b5119',
    messagingSenderId: '1060937525212',
    projectId: 'jobscope-app',
    storageBucket: 'jobscope-app.firebasestorage.app',
  );
}
